### ISSUE TITLE
Some components unavailable with high lead time.

### ISSUE THREAD

**Issue by Relys** [hydromisc/hydromisc#6]
Hey, I'm looking to build one of these and noticed that a few components are unavailable on digikey due to the chip shortage. Are there any alternatives I could use?

1724480008
SS34B-HF
LM2596DSADJR4G
LM4041CYM3-1.2-TR
AZ1117IH-3.3TRG1
DMG2302UK-7

**Comment by hydromisc** [comment]
1724480008 - 0039301081
SS34B-HF - any Schottky diode with same or greater voltage and current rating
LM2596DSADJR4G - Mouser
LM4041CYM3-1.2-TR - Mouser
AZ1117IH-3.3TRG1 - NCV1117ST33T3G
DMG2302UK-7 - any logic-level n-FET with same or greater voltage and current rating

Please double-check the new part numbers yourself too. Let me know how the build goes, or if you want me to double-check your replacement Schottky/FET.

**Comment by godzillachan** [comment]
Came across this project during my search on hydroponics controllers and I am interested in producing small quantities of these boards.  Can we get in touch?

**Comment by hydromisc** [comment]
This is open hardware, so please feel free to build. If you have questions then you can just ask here or on reddit (/u/lathyrus_long).
