### ISSUE TITLE
Not a bug…

### ISSUE THREAD

**Issue by G4KCM** [hydromisc/hydromisc#7]
Don’t think GitHub supports a THANK YOU but I would just like to express my appreciation to the developer as this is a really nice controller.  Couple of points for those who may be interested.  I used an ESP32 with an external antenna which is useful if you have a poor WiFi signal where you want to place it.  I also found that the latest v5 version of the Expressif toolchain throws a lot of errors.  Rather than mess with the (very eloquent) code I reverted to v4.2.1. which was released circa the time this project was released into GitHub and thus far seems all ok (just awaiting an AM2301) to complete the check out.

I’m interfacing to it via node-red and Home Assistant.

A very professionally designed and documented piece of work, thank you once again! 

![IMG_2534](https://github.com/hydromisc/hydromisc/assets/17541578/00134d25-5bc2-44d7-8cdf-68a0022083b5)

**Comment by hydromisc** [comment]
Thanks, and your build looks good. You might post some pictures on /r/hydroponics once you assemble that with the pumps and such, since they tend to like that kind of stuff. The Home Assistant interface might also be of interest to others, if you wanted to publish that.
